### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by valentinvanelslande** [aslze/asl#6]
macOS:
```
/Users/travis/build/valentinvanelslande/citra/externals/asl/src/Directory.cpp:266:35: error: use of undeclared identifier 'PATH_MAX'
        char* d = getcwd(SafeString(dir, PATH_MAX), PATH_MAX);
                                         ^
/Users/travis/build/valentinvanelslande/citra/externals/asl/src/Directory.cpp:266:46: error: use of undeclared identifier 'PATH_MAX'
        char* d = getcwd(SafeString(dir, PATH_MAX), PATH_MAX);
```

Compiling for Windows on Linux:
```
/citra/externals/asl/src/Socket.cpp:6:10: fatal error: WinSock2.h: No such file or directory
 #include <WinSock2.h>
          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by aslze** [comment]
The macOS issue is fixed.

But I don't understand the other issue: <WinSock2.h> is a normal Windows SDK header. Works on VS2005 to VS2017, MinGW, etc.

Well, I've never done such Linux/Windows cross compiling. Maybe it's due to **case sensitivity** on the Linux file system? Does it work with `#include <winsock2.h>` lowercased?

(I don't know why I capitalized it that way but on Windows it does not matter anyway).

**Comment by valentinvanelslande** [comment]
@aslze yes it works with lower case, all the fixes are in my fork:
f5c3fc1d5b6a70bd008494994e287ce8c9faa8f5
f3faecb3957e9c7370559401532fc94018f71d6a
a5dcb7672845f5884a529d5b4c62285d7c2361ee
don't use define, use this:
```cpp
#ifdef __APPLE__
#include <sys/syslimits.h>
#endif
```

**Comment by aslze** [comment]
Thanks!
