### ISSUE TITLE
SocketServer can be destroyed before SockClientThread workers ends

### ISSUE THREAD

**Issue by xjrsanchezx** [aslze/asl#9]
There is no way to check if any SockClientThread is still working before destroying a SocketServer. The running() method only checks that the main loop of the server thread has been stoped after calling stop(), but a SockClientThread  may be still working. If the server is destroyed with a SockClientThread it will SEGFAULT. A method to check that every SockClientThread has finished will be valuable in order to shutdown a server safely.

Thanks!

**Comment by aslze** [comment]
I'm not yet sure why/when that crashes. I guess when the client thread accesses data members of the server object.

I can make the server object always wait until a client thread counter reaches zero. And add a way for clients to know that the server has been requested to stop, so they can end what they are doing.

**Comment by xjrsanchezx** [comment]
> I'm not yet sure why/when that crashes. I guess when the client thread accesses data members of the server object.

That's the reason

> I can make the server object always wait until a client thread counter reaches zero. And add a way for clients to know that the server has been requested to stop, so they can end what they are doing.

It would be a good solution. Thanks!

**Comment by aslze** [comment]
There are improvements in this area in version 1.9.2. But subclasses of SocketServer have to collaborate to be stoppable.

Now you can call `SocketServer::stop()` and the server will exit its loop and client serving threads will also exit if they collaborate. You can call `stop(true)` to stop and wait until all those exit. Or you can call `running()` after `stop()` to check if it is still running or has active clients that have not yet exited.

One key to this is that socket input waiting functions need a lower timeout so that they can check regularly if `_requestStop` is true, and exit their loops.

SocketServer subclasses have to also check this flag regularly by also using not too long timeouts (a few seconds maybe). The recommended `serve()` function loop for long-running services would be like this:

```cpp
void serve(Socket client)
{
	while (!client.disconnected() && !_requestStop)
	{
		if (!client.waitData(2))
			continue;
		String line = client.readLine(); // or other reading operation
		...
	}
}
```

(Current issue: The `SocketServer` destructor does not call `stop()` so it is now up to subclasses or apps to do this).
